### ISSUE TITLE
Sending payments

### ISSUE THREAD

**Issue by mvd010** [link0/bunq#23]
Hi,

I'm trying yo send payments to IBAN with this API wrapper, but can't quite get it working. Can someone help me out?

In the console on https://doc.bunq.com/api/1/call/payment/method/post I get it working by posting:
`{
"amount": {
"value": "12.50",
"currency": "EUR"
},
"counterparty_alias": {
"type": "IBAN",
"name": "J. Lastname",
"value": "NLXXXXXX0123456789"
},
"description": "Payment for drinks."
}`
to POST https://public.api.app51.dev1.nl1.bunq.net/v1/user/1951/monetary-account/1971/payment
headers

**Comment by dennisdegreef** [comment]
Hi @mvd010 

Currently this functionality is not built in yet, however, I think it's easily integrable.
If you could take a look, pull requests are most welcome.
If not, I think I can take a look at it within a few days.

Thanks for your question, this helps me focus on different use cases.
Feedback is also much appreciated.

**Comment by dennisdegreef** [comment]
Hi @mvd010 

I just went along and implement is, I am however currently not in the opportunity to test it.
You could help me by testing this branch, by going to `./vendor/link0/bunq/` and switching the branch by running the following commands:

```
$ git fetch origin pull/24/head:add_payment
$ git checkout add_payment
```

A review on the pull request is welcome as well.

**Comment by mvd010** [comment]
Hi @dennisdegreef,

I'll take a look as soon as I have time to work on this project again!
Thanks!

**Comment by dennisdegreef** [comment]
Hi @mvd010 

Did you have any time to work on that project since then?
I will just merge this change, since it is fully backwards compatible and new behaviour.
I'd love to hear back from you in any case though. But please add an issue if it doesn't :)

**Comment by dennisdegreef** [comment]
PR is merged, please let me know if you have found time to test it.
Thanks for your suggestion!
